### PR TITLE
Bug fix #5

### LINKED ISSUE #5: Android App does not show profile images
- HTTPS issue?

### PR DESCRIPTION
**Pull request by ztirom**
This fix resolves #5 “Android App does not show profile images”

screen shot 2016-12-11 at 16 23 54

### CODE REVIEW

**Comment by robinmanuelthiel** [comment]
Hi Moritz, thanks a lot for your work. Please help me to understand, what you did here. As far as I can see, you just

- Created an impl. of `IHttpService` in the Android project, that uses the native HTTP implementation
- Provide this impl. to the `ConferenceService`
- Enabled the `INTERNET` permission in the Android Manifest

What I don't get here: Why does this enable the image download? The `DroidHttpService` is just responsible for downloading the JSON, not the image itself, right? The image is downloaded by the `Xamarin.Forms.Image` control inside the `ImageCell`.

So where do you tell the Android system to always use the native HTTP implementation, **even** in the `ImageCell`?

**Comment by ztirom** [comment]
Hi Robin-Manuel,

you are right, there is no issue with downloading the data, all it takes is the default implementation of the handler that is declared by the line in the "**Environment**" txt file:
`XA_HTTP_CLIENT_HANDLER_TYPE=Xamarin.Android.Net.AndroidClientHandler`

**Comment by robinmanuelthiel** [comment]
Ah okay, I get it, thanks! I am still a little bit confused, because what I already tried to solve this problem was selecting the `AndroidClientHandler` as the HttpClient Implementation under **Project Properties** > **Android Options**. According to [this article from Xamarin](https://developer.xamarin.com/guides/cross-platform/transport-layer-security/#Xamarin.Android), it should de exactly the same as adding this `Envorionment.txt` file. But the settings does not work and your file does. Weird...

Alright, could you please adjust your Pull request, sothat the changes are only three new files in the Android project of the **Conference App with Xamarin.Forms**, **Connecting to the Cloud** and **Optimizations and Tweaks** module? I want to keeps things as simple as possible!

Then it can merge your PR easily and add the desctiption! Again, thanks a lot!

**Comment by ztirom** [comment]
Good Morning, the `Environment` files are now the only files on the PR. 
Thank you and have a nice day.

**Comment by robinmanuelthiel** [comment]
Great! Thank you very much, especially for the effort, but also for the clearification and time! Great work!

**Pull request merged**
